//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stremacup.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class match
    {
        public long id { get; set; }
        public Nullable<long> score1 { get; set; }
        public Nullable<long> score2 { get; set; }
        public Nullable<System.DateTime> datetime { get; set; }
        public long team1_fk { get; set; }
        public long team2_fk { get; set; }
        public Nullable<long> field_fk { get; set; }
    
        public virtual team team { get; set; }
        public virtual team team1 { get; set; }
        public virtual field field { get; set; }
    }
}
