//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stremacup.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class stremacupEntities : DbContext
    {
        public stremacupEntities()
            : base("name=stremacupEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<category> category { get; set; }
        public DbSet<field> field { get; set; }
        public DbSet<group> group { get; set; }
        public DbSet<match> match { get; set; }
        public DbSet<matchday> matchday { get; set; }
        public DbSet<place> place { get; set; }
        public DbSet<schedule> schedule { get; set; }
        public DbSet<team> team { get; set; }
    }
}
