//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stremacup.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class place
    {
        public place()
        {
            this.field = new HashSet<field>();
        }
    
        public long id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<field> field { get; set; }

        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();

            stringBuilder.Append(String.Format("Place Name: {0}, (", this.name));

            foreach (field field in this.field)
            {
                stringBuilder.Append(String.Format("{0}, ", field.name));
            }

            stringBuilder.Append(")");

            return stringBuilder.ToString();
        }
    }
}
