//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stremacup.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class schedule
    {
        public long id { get; set; }
        public System.DateTime beginHour { get; set; }
        public System.DateTime endHour { get; set; }
        public Nullable<long> matchday_fk { get; set; }
    
        public virtual matchday matchday { get; set; }

        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
 
            stringBuilder.Append(String.Format("{0,2:D2}:{1,2:D2}", this.beginHour.Hour, this.beginHour.Minute));
            stringBuilder.Append(" - ");
            stringBuilder.Append(String.Format("{0,2:D2}:{1,2:D2}", this.endHour.Hour, this.endHour.Minute));

            return stringBuilder.ToString();
        }
    }
}
