//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stremacup.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class schedule
    {
        public long id { get; set; }
        public System.DateTime beginHour { get; set; }
        public System.DateTime endHour { get; set; }
        public Nullable<long> matchday_fk { get; set; }
    
        public virtual matchday matchday { get; set; }
    }
}
