//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stremacup.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class team
    {
        public team()
        {
            this.match = new HashSet<match>();
            this.match1 = new HashSet<match>();
        }
    
        public long id { get; set; }
        public string name { get; set; }
        public Nullable<long> group_fk { get; set; }
    
        public virtual group group { get; set; }
        public virtual ICollection<match> match { get; set; }
        public virtual ICollection<match> match1 { get; set; }
    }
}
